## rabbitmq producer≈‰÷√
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true #“Ï≤Ωº‡Ã˝rabbitmq brokerΩ·π˚
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 1qaz@WSX
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8001
  servlet:
    context-path: /
mybatis:
  mapper-locations: classpath:mapper/*.xml